sudo: false
language: java
jdk:
  - oraclejdk8
install: true
cache:
  directories:
    - $HOME/.m2
script: ./mvnw clean install jacoco:report jacoco:report-aggregate coveralls:report
        