sudo: false
language: java
jdk:
  - oraclejdk8
  - openjdk8
install: true
cache:
  directories:
    - $HOME/.m2
script: mvn clean install jacoco:report jacoco:report-aggregate coveralls:report
        