language: java
# use Java 8
jdk:
  - openjdk8

sudo: false

# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

before_install:
   - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V 

script:  
  - mvn clean test jacoco:report jacoco:report-aggregate coveralls:report 