language: java
# use Java 8
jdk:
  - openjdk8

sudo: true

# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

script:  "mvn clean test jacoco:report jacoco:report-aggregate coveralls:report" 